language: node_js
node_js:
  - "11"
cache:
  directories:
    - "node_modules"
install:
  - yarn install
env:
  global:
    - NODE_ENV=test
    - JWT_SECRET=secret_key

before_script:
  - yarn run build
script:
  - yarn test
after_success:
<<<<<<< HEAD
  - npm run coveralls
=======
  - coveralls < coverage/lcov.info
>>>>>>> Adding coveralls
